import Ember from 'ember';
import SessionService from 'ember-simple-auth/services/session';

const {
  inject: { service },
} = Ember;


export default SessionService.extend({

  store: service(),

  /**
   * User record to be created/found upon authentication
   */
  user: null,


  /**
    Authorizes a block of code with an authorizer (see
    {{#crossLink "BaseAuthorizer/authorize:method"}}{{/crossLink}}) if the
    session is authenticated. If the session is not currently authenticated
    this method does nothing.
    ```js
    this.get('session').authorize('authorizer:oauth2-bearer', (headerName, headerValue) => {
      xhr.setRequestHeader(headerName, headerValue);
    });
    ```
    @method authorize
    @param {String} authorizer The authorizer to authorize the block with
    @param {Function} block The block of code to call with the authorization data generated by the authorizer
    @public
  */
  authorize (/* authorizerFactory, block */) {
    this._super(...arguments);
  },

});
